In [1]:
import numpy as np
import ndlib.nn as nn
import ndlib.functional as F

In [2]:
l1 = nn.Linear(8, 8, activation='relu')
l2 = nn.Linear(8, 4, activation='relu')
l3 = nn.Linear(4, 2, activation='softmax')

In [3]:
X = np.random.randn(8, 2)

In [4]:
t = l1(X)

In [5]:
print(l1.Z)
print(l1.A)

[[-3.47992916  2.22282952]
 [-3.59009892  1.54210291]
 [-1.18176037 -1.06920527]
 [ 1.03864714  2.98629908]
 [-0.51477541 -2.07359479]
 [-0.4583855   0.49705435]
 [-4.04194505  4.4088225 ]
 [-4.87938521  4.56007618]]
[[0.         2.22282952]
 [0.         1.54210291]
 [0.         0.        ]
 [1.03864714 2.98629908]
 [0.         0.        ]
 [0.         0.49705435]
 [0.         4.4088225 ]
 [0.         4.56007618]]


In [6]:
t.shape

(8, 2)

In [7]:
t = l2(t)


In [8]:
t.shape

(4, 2)

In [9]:
t = l3(t)

In [10]:
print(t)

[[7.03647304e-01 9.99864212e-01]
 [2.96352696e-01 1.35788251e-04]]


In [11]:
x = l3.Z
print(x)

[[ 0.17890122  1.29486523]
 [-0.68582574 -7.60941284]]
