In [1]:
import numpy as np
import ndlib.nn as nn
import ndlib.functional as F

In [2]:
l1 = nn.Linear(8, 8, activation='relu')
l2 = nn.Linear(8, 4, activation='relu')
l3 = nn.Linear(4, 2, activation='softmax')

In [3]:
X = np.random.randn(8, 2)

In [4]:
t = l1(X)

In [5]:
print(l1.Z)
print(l1.A)

[[ 4.04871074e+00  3.37626490e+00]
 [ 5.13257598e-01  5.79882888e-01]
 [-2.71909866e+00 -2.02670316e+00]
 [ 1.92951437e+00 -3.58934121e-03]
 [ 2.11103569e+00  2.03084126e+00]
 [-7.29032961e-01  2.65626616e-01]
 [ 5.69595558e-01 -3.84928494e-01]
 [ 7.78487969e-01  1.47299764e+00]]
[[4.04871074 3.3762649 ]
 [0.5132576  0.57988289]
 [0.         0.        ]
 [1.92951437 0.        ]
 [2.11103569 2.03084126]
 [0.         0.26562662]
 [0.56959556 0.        ]
 [0.77848797 1.47299764]]


In [6]:
t.shape

(8, 2)

In [7]:
t = l2(t)


In [8]:
t.shape

(4, 2)

In [9]:
t = l3(t)

In [10]:
print(t)

[[0.91514847 0.91514847]
 [0.08485153 0.08485153]]


In [11]:
x = l3.Z
print(x)

[[-0.19538082 -0.19538082]
 [-2.57356405 -2.57356405]]
